[package]
name = "lifo"
version = "0.1.1"
edition = "2021"
description = "Simple last-in first-out api wrapper for std `VecDeque<T>`."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Da1sypetals/lifo"

[dependencies]
